// pages/about.vue
<script setup lang="ts">
const { t } = useI18n({
  useScope: 'local'
});

</script>
<template>
  <div id="about" class="max-w-full container px-4 md:px-10">
    <div class="hero-content flex-col md:flex-row-reverse px-0 mx-0 max-w-full">
      <img alt="Headshot" src="/eu.png" id="eu" class="rounded-lg shadow-2xl" />
      <div>
        <h2 class="font-bold" style="font-size: 1.875rem;">{{ t('about') }}</h2>
        <p>
          {{ t('about_text') }}
        </p>
        <NuxtLink to="/about" class="btn btn-primary md:btn-sm mt-2">
          {{ $t('more') }}
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<style>
#about {
  padding-top: 90px;
  padding-bottom: auto;
  max-height: 800px;
}

#eu {
  height: auto;
  max-width: 200px;
  border-radius: 8px;
  margin: auto;
}

.transition {
  background: linear-gradient(180deg,
      transparent -50%,
      oklch(var(--a)) 20%,
      oklch(var(--a)) 80%,
      transparent 150%);
  height: inherit;
  min-width: 4px;
  width: 4px;
}

@media (min-width: 768px) {
  #about {
    margin: auto;
    height: auto;
  }
}
</style>

<i18n lang="json">{
  "pt": {
    "about": "Sobre mim",
    "about_text": "Eu sou Vinícius, um estudante de Ciência da Computação e desenvolvedor trabalhando com PHP, MySQL e Flutter. Durante a graduação tive a oportunidade de aprender programação desde C e C++ a Java e Python. Fazendo minha Iniciação Científica em robótica também passei a conhecer melhor sobre dispositivos IoT e Arduino."
  },
  "en": {
    "about": "About me",
    "about_text": "I'm Vinícius, a Computer Science student and developer working with PHP, MySQL and Flutter. During graduation I had the opportunity to learn programming from C and C++ to Java and Python. Doing my Scientific Initiation in robotics, I also got to know better about IoT devices and Arduino."
  },
  "de": {
    "about": "Über mich",
    "about_text": "Ich bin Vinícius, ein Informatikstudent und Entwickler, der mit PHP, MySQL und Flutter arbeitet. Während meines Abschlusses hatte ich die Gelegenheit, Programmieren von C und C++ bis hin zu Java und Python zu lernen. Während meiner wissenschaftlichen Einführung in Robotik lernte ich auch IoT-Geräte und Arduino besser kennen."
  }
}</i18n>

// src/lib/about.svelte
<div class=" mt-20 md:mt-0 md:content-center" id="about">
<h2>Sobre mim</h2>
<div class="grid grid-cols-1 md:grid-cols-3 gap-4" style="height: 100%;">
	<div class="col md:col-span-2 c-prose" style="height: fit-content;">
		<p>
			Eu sou o Vinícius, um estudante de Ciência da Computação e estagiário trabalhando com PHP,
			MySQL e FLutter. Durante a graduação tive a oportunidade de aprender programação desde de C e
			C++ a Java e Python. Fazendo minha Iniciação Científica em robótica também passei a conhecer
			melhor sobre dispositivos IoT e especialmente Arduino.
			<br />
			Normalmente passo meu tempo lendo, jogando, ouvindo música e, como todo bom programador, criando
			algum novo projeto que nunca será finalizado.
		</p>
	</div>
	<div class="col content-center" >
		<img alt="Headshot" src="eu.png" id="eu" />
	</div>
</div>
</div>
<style>
	#about {
		padding-top: auto;
		padding-bottom: auto;
		height: 100vh;
		max-height: 800px;
	}

	#eu {
		width: 100%;
		height: auto;
		max-width: 200px;
		border-radius: 8px;
		margin: auto;
	}

	#about h2 {
		font-size: 1.6666667em;
		line-height: 4/3;
		font-weight: 700;
	}
	
	@media (min-width: 768px) {
		.c-prose {
			font-size: 1.125rem;
		}
		#about {
			margin: auto;
			/* padding-bottom: auto; */
			height: auto;
		}
	}
</style>
